env:
  TERM: xterm-256color

window:
  dynamic_title: true
  dimensions:
    columns: 240
    lines: 60
  padding:
    x: 4
    y: 4
  dynamic_padding: true
  startup_mode: SimpleFullscreen

title: Terminal

font:
  use_anti_alias: false
  size: 12.0
  offset:
    x: 0
    y: 0
  normal:
    family: Source Code Pro for Powerline
    style: Regular
  bold:
    family: Source Code Pro for Powerline
    style: Bold
  italic:
    family: Source Code Pro for Powerline
    style: Italic
  bold_italic:
    family: Source Code Pro for Powerline
    style: Bold Italic


background_opacity: 0.7

cursor:
  style: Underline

live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux -u -f $HOME/.tmux.conf attach -t login-shell 2>/dev/null || tmux -u -f $HOME/.tmux.conf new -s login-shell \\; split-window -h \\; split-window -v \\; select-pane -L"

working_directory: /
key_bindings:
  - { key: Left,     mods: Alt,     chars: "\e[1;5D" }
  - { key: Right,    mods: Alt,     chars: "\e[1;5C" }
  - { key: Q,    mods: Command,     chars: "\x1bq" }

# Monokai Pro (edited)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#FCFCFA'

  # Normal colors
  normal:
    black:   '#403E41'
    red:     '#FF6188'
    green:   '#A9DC76'
    yellow:  '#FFD866'
    blue:    '#FC9867'
    magenta: '#AB9DF2'
    cyan:    '#78DCE8'
    white:   '#FCFCFA'

  # Bright colors
  bright:
    black:   '#727072'
    red:     '#FF6188'
    green:   '#A9DC76'
    yellow:  '#FFD866'
    blue:    '#FC9867'
    magenta: '#AB9DF2'
    cyan:    '#78DCE8'
    white:   '#FCFCFA'
