env:
  TERM: alacritty

window:
  opacity: 0.9
  dynamic_title: true
  dimensions:
    columns: 120
    lines: 40
  padding:
    x: 4
    y: 4
  dynamic_padding: true
  startup_mode: Windowed

font:
  size: 9
  offset:
    x: 0
    y: 1
  normal:
    family: HackGen35 Console NF
    style: Regular
  bold:
    family: HackGen35 Console NF
    style: Bold
  italic:
    family: Source Code Pro for Powerline
    style: Italic
  bold_italic:
    family: Source Code Pro for Powerline
    style: Bold Italic

cursor:
  style:
    shape: Underline
    blinking: Always

live_config_reload: true

decorations: buttonless


shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - |
      tmux -u -f $HOME/.tmux.conf


working_directory: /
key_bindings:
  - { key: Left,     mods: Alt,     chars: "\e[1;5D" }
  - { key: Right,    mods: Alt,     chars: "\e[1;5C" }
  - { key: Q,    mods: Command,     chars: "\x1bq" }

# Monokai Pro (edited)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#FCFCFA'

  # Normal colors
  normal:
    black:   '#727072'
    red:     '#FF6188'
    green:   '#A9DC76'
    yellow:  '#FFD866'
    blue:    '#AB9DF2'
    magenta: '#f54966'
    cyan:    '#78DCE8'
    white:   '#FCFCFA'

  # Bright colors
  bright:
    black:   '#727072'
    red:     '#FF6188'
    green:   '#A9DC76'
    yellow:  '#FFD866'
    blue:    '#AB9DF2'
    magenta: '#f54966'
    cyan:    '#78DCE8'
    white:   '#FCFCFA'
