env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 240
    lines: 60
  padding:
    x: 4
    y: 4
  dynamic_padding: true
  startup_mode: Windowed

title: Terminal

font:
  use_anti_alias: false
  size: 12.0
  offset:
    x: 0
    y: 0
  normal:
    family: Source Code Pro for Powerline
    style: Regular
  bold:
    family: Source Code Pro for Powerline
    style: Bold
  italic:
    family: Source Code Pro for Powerline
    style: Italic
  bold_italic:
    family: Source Code Pro for Powerline
    style: Bold Italic


background_opacity: 0.825
dynamic_title: true

cursor:
  style: Underline

live_config_reload: true

shell:
  program: /bin/zsh

  args:
    - -l
    - -c
    - "tmux -u -f $HOME/.tmux.conf attach -t login-shell || tmux -u -f $HOME/.tmux.conf new -s login-shell \\; split-window -v \\; split-window -h \\; select-pane -L \\; select-pane -U \\; split-window -h \\; select-pane -L \\;"

working_directory: /
key_bindings:
  - { key: Left,     mods: Alt,     chars: "\e[1;5D" }
  - { key: Right,    mods: Alt,     chars: "\e[1;5C" }
  - { key: Q,    mods: Command,     chars: "\x1bq" }
