env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 260
    lines: 50
  padding:
    x: 4
    y: 4
  dynamic_padding: true
  startup_mode: SimpleFullscreen

title: Terminal

tabspaces: 2

font:
  use_anti_alias: true
  size: 10.0
  offset:
    x: 0
    y: 1
  normal:
    family: Source Han Code JP R
  bold:
    family: Source Han Code JP B
    style: Bold
  italic:
    family: Source Han Code JP I
    style: Italic
  bold_italic:
    family: Source Han Code JP B
    style: Bold Italic


background_opacity: 0.9
dynamic_title: true

cursor:
  style: Underline

live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux kill-session -t login-shell && tmux -u -f ~/.tmux.conf attach -t login-shell || tmux -u -l -f ~/.tmux.conf new -s login-shell \\; split-window -v \\; split-window -h \\; split-window -v \\; select-pane -L \\; select-pane -U \\; split-window -h \\; select-pane -L \\;"

working_directory: /
key_bindings:
  - { key: Left,     mods: Alt,     chars: "\e[1;5D" }
  - { key: Right,    mods: Alt,     chars: "\e[1;5C" }
