# Aliases
alias pip='/usr/local/bin/pip3'
alias python='/usr/local/bin/python3'
alias xxd='hexyl'
alias tree='tree -a'
alias sed='gsed'
alias cat='bat'
alias q='pbcopy'
alias qq='pbpaste'
alias t='twterm'
alias grep='rg -n'
alias tkw='tmux kill-window'
alias tks='tmux kill-server'
alias tnw='tmux new-window'
alias vim='nvim'
alias top='procs --watch --insert TcpPort --sortd cpu'
alias ps='procs --color=disable --sorta pid'
alias cloc='tokei'
alias du='dust'
alias htop='btm'
alias cp='cpz'
alias rm='rmz'

# copy-and-paste aliases
alias p='pwd | q'
alias pp='cd $(qq) && p'
alias pg='_get_git_branch | q';
